services:
  mongo:
    image: mongodb/mongodb-atlas-local:8.0
    container_name: bbr-mongo
    ports:
      - "${MONGO_HOST_PORT:-27017}:27017"
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USER:-bbr}
      - MONGODB_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASS:-bbrpass}
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    networks:
      - bbr-net
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bbr-api
    env_file:
      -  ./backend/.env
    environment:
      - USE_MONGO=${USE_MONGO:-1}
      - MONGODB_URI=${MONGODB_URI:-mongodb://bbr:bbrpass@mongo:27017/?directConnection=true}
    ports:
      - "8000:8000"
    networks:
      - bbr-net
    depends_on:
      - mongo

  form-corrector:
    build:
      context: ./form-corrector
      dockerfile: Dockerfile
    container_name: bbr-form-corrector
    ports:
      - "9000:9000"
    networks:
      - bbr-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # Point frontend to compose-internal URL for form-corrector
        REACT_APP_FORM_CORRECTOR_URL: /form-corrector
    container_name: bbr-frontend
    ports:
      - "3000:80"
    depends_on:
      - api
      - form-corrector
    networks:
      - bbr-net
volumes:
  mongo-data:
  mongo-config:
networks:
  bbr-net:
    name: bbr-net
